version: '3.8'

services:
  windows-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - windows-build-cache:/home/vscode/.cache
      - ../../windows:/workspaces/windows:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    networks:
      base_net:
        ipv4_address: 172.30.0.32
volumes:
  windows-build-cache:
networks:
  base_net:
    external: true